# Generated by Django 5.0.6 on 2024-06-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Штуки'), ('kg', 'Килограммы'), ('l', 'Литры')], default='pcs', max_length=3),
        ),
    ]
